### ISSUE TITLE
发现一个BUG

### ISSUE THREAD

**Issue by BloothOfYouth** [hikerpig/toc-bar-userscript#1]
如果h标签内的内容一样，生成的id也会是一样，这样重复的id的h标签只会跳转到第一个重复id的h标签
![1602389390(1)](https://user-images.githubusercontent.com/58901075/95670664-c912a200-0bc0-11eb-8d86-a874b6fb8dba.jpg)

**Comment by hikerpig** [comment]
@BloothOfYouth  是的，因为 id 是内容的简易哈希值。我本以为这种情况不会很常见，你碰上了的话... 我稍微改一改吧

**Comment by hikerpig** [comment]
@BloothOfYouth 更新完毕，试试 1.5.0 有没有解决你的问题

**Comment by BloothOfYouth** [comment]
@hikerpig OK,解决了，谢谢 O(∩_∩)O~~
