### ISSUE TITLE
登录 GitHub 后脚本变得无效

### ISSUE THREAD

**Issue by xtmu** [hikerpig/toc-bar-userscript#17]
不登录 GitHub 时脚本有效，登录 GitHub 后脚本无效。在 Firefox 119 和 chromium 上测试了都出现这种情况，最近一个月内出现的。只对于 GitHub ，在其他网站上正常。

**Comment by xtmu** [comment]
![image](https://github.com/hikerpig/toc-bar-userscript/assets/90405292/6dc5a63b-9f7f-4912-9b25-7887e8578b41)

**Comment by hikerpig** [comment]
emm 可能是 github 改版了

**Comment by hikerpig** [comment]
1.9.6 版本修复了 github 项目主页看不到内容的问题
