### ISSUE TITLE
考虑支持 github issue 吗？

### ISSUE THREAD

**Issue by superleeyom** [hikerpig/toc-bar-userscript#2]
挺实用的插件，已经用上了，要是能支持 github issue 就好了，因为好多人在 issue 上写博客（我也是），但是没有目录，有点影响阅读体验，如果能支持就好了，望考虑

**Comment by hikerpig** [comment]
安排上，支持起来应该不难

**Comment by superleeyom** [comment]
@hikerpig cool

**Comment by superleeyom** [comment]
@hikerpig 嗨，反馈一个问题
![image](https://user-images.githubusercontent.com/22115219/106687625-75144900-6607-11eb-8d4f-2eac1cedeea1.png)
toc实际高亮的标题和跳转的标题没有对应上，是不是有点问题呢？
文章：https://github.com/superleeyom/blog/issues/15

**Comment by hikerpig** [comment]
@superleeyom 还真是... 我看看，找个长点的 issue 修复一下...

**Comment by superleeyom** [comment]
我这边又发现了一个比较致命的问题，就是移动toc面板的时候，会出现浮动的toc面板不见了，后面怎么刷新都不显示了，只能重新卸载脚本，重新安装，很容易复现，目前使用的浏览器是最新的版本的chrome，系统是 macOS big sur 11.1 
![image](https://user-images.githubusercontent.com/22115219/106860102-e256d580-66fe-11eb-85dc-a613413db4a4.png)

**Comment by hikerpig** [comment]
这个操作好极限... 其实左上角那一丢丢还是可以点的，不过我改一下吧，最多拖到 icon 右边缘触到屏幕边缘

**Comment by superleeyom** [comment]
> @superleeyom 还真是... 我看看，找个长点的 issue 修复一下...

这个问题排查的咋样了？

**Comment by hikerpig** [comment]
> > @superleeyom 还真是... 我看看，找个长点的 issue 修复一下...
> 
> 这个问题排查的咋样了？

今天有空的话晚上修复一下。

**Comment by superleeyom** [comment]
@hikerpig cool，谢谢

**Comment by hikerpig** [comment]
1.7.0试试

**Comment by superleeyom** [comment]
> 1.7.0试试

好的，我试试哈，多谢了

**Comment by superleeyom** [comment]
刚更新用了下，点击最后一个的时候，似乎没有定位上，其他的都定位上了
![image](https://user-images.githubusercontent.com/22115219/106982402-09fd7a80-679f-11eb-99ca-fc5d2fa605e9.png)
issue：https://github.com/superleeyom/blog/issues/12

**Comment by superleeyom** [comment]
@hikerpig

**Comment by superleeyom** [comment]
比较神奇，我在我的mbp（白苹果 macOS Big Sur 11.1）上访问issue：https://github.com/superleeyom/blog/issues/12 又是正常的，在公司的电脑上（黑苹果 macOS Big Sur 11.1）上点击 toc bar 最后一个 title，无法进行定位 @hikerpig

**Comment by hikerpig** [comment]
最后一个定不到是因为滚动条已经触底了吧？

**Comment by superleeyom** [comment]
> 最后一个定不到是因为滚动条已经触底了吧？

好像是这么回事：
![image](https://user-images.githubusercontent.com/22115219/106988200-1fc46d00-67aa-11eb-8dc9-7d6dd85deff0.png)

**Comment by superleeyom** [comment]
@hikerpig

**Comment by hikerpig** [comment]
@superleeyom  那就没有别的问题了😎

**Comment by superleeyom** [comment]
> @superleeyom 那就没有别的问题了😎

排查到是啥问题了呢？有空就修复下呗？？？

**Comment by hikerpig** [comment]
如果触底情况下内容标题'资料'还在 github 这个 header 底下，是无法定位的，这个浏览器行为没必要去 hack

**Comment by superleeyom** [comment]
> 如果触底情况下内容标题'资料'还在 github 这个 header 底下，是无法定位的，这个浏览器行为没必要去 hack

@hikerpig ok，那谢谢了，我先关掉issue吧

**Comment by superleeyom** [comment]
脚本是已经对掘金失效了？似乎没有触发脚本，没有浮动toc目录
