### ISSUE TITLE
对掘金失效

### ISSUE THREAD

**Issue by hikerpig** [hikerpig/toc-bar-userscript#3]
目测是掘金改版了，需要调整下。

CC @superleeyom ，等我写完绩效评估明天看看 😂

**Comment by superleeyom** [comment]
ok，辛苦了哈 @hikerpig

**Comment by hikerpig** [comment]
@superleeyom 走之前快速看了眼，掘金现在已经有 toc 了，是不是我这个就不需要了呀？

**Comment by superleeyom** [comment]
> @superleeyom 走之前快速看了眼，掘金现在已经有 toc 了，是不是我这个就不需要了呀？
哈哈，那就去掉吧，既然有了，免得重复造轮子，谢谢

**Comment by superleeyom** [comment]
那就去掉吧，免得重复造轮子，辛苦了
