### ISSUE TITLE
[bug]图标不跟着鼠标走，有点飘~

### ISSUE THREAD

**Issue by superleeyom** [hikerpig/toc-bar-userscript#4]
我又来反馈bug了，如下gif所示：
![](http://image.leeyom.top/blog/2021-03-26%2011.47.06.gif)

**Comment by hikerpig** [comment]
今天周末，等上班了我有时间重现一下哈(๑`･ᴗ･´๑)

**Comment by hikerpig** [comment]
我好像没能重现出来这个问题，是在 issues 页面吧？那应该是没有内容导致的？
正常有内容的情况下会出现这个问题么？

**Comment by superleeyom** [comment]
正常情况下也有可能出现这个问题，就像那个gif一样，飘的非常厉害，图标不跟鼠标走，这种情况下，只能重新安装脚本才行

**Comment by hikerpig** [comment]
1.重新安装脚本是一定会好么？
2.然后用着用着就会又出问题？
3.出问题之前有没有什么典型操作，例如调整窗口大小之类
4.操作系统和浏览器的版本是？
我只能瞎猜原因

**Comment by superleeyom** [comment]
> 1.重新安装脚本是一定会好么？
> 2.然后用着用着就会又出问题？
> 3.出问题之前有没有什么典型操作，例如调整窗口大小之类
> 4.操作系统和浏览器的版本是？
> 我只能瞎猜原因

1. 重装脚本一定会好
2. 这个问题不太好复现，有时候靠边，拖动幅度较大的时候，就会出现gif那种情况，这个问题应该是真的存在，就是不知道怎么触发出来，可能偶发性的吧，你那边有这个问题吗？
3. 操作系统是 macOS Big sur 11.0.1，浏览器是最新版本的chrome 89，屏幕分辨率 1080p
